# Generated by Django 4.1.6 on 2023-02-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datacompleted',
            new_name='datecompleted',
        ),
    ]
